In [ ]:
import pandas as pd
import numpy as np

# Load detection file
# Adjust path as needed
df = pd.read_csv(
    "combined_det.csv",
    sep=r"\s+|,",
    header=None,
    engine="python"
)

# Assign column names based on dataset spec
df.columns = [
    "frame",
    "object_id",
    "x",
    "y",
    "width",
    "height",
    "confidence",
    "ignore_1",
    "ignore_2",
    "ignore_3",
    "Swarm"
]

df.head()

,frame,object_id,x,y,width,height,confidence,ignore_1,ignore_2,ignore_3,Swarm
0,1,-1,117,145,31,25,1,-1,-1,-1,UAVSwarm-09
1,1,-1,218,67,38,35,1,-1,-1,-1,UAVSwarm-09
2,1,-1,224,187,30,20,1,-1,-1,-1,UAVSwarm-09
3,1,-1,323,143,32,23,1,-1,-1,-1,UAVSwarm-09
4,2,-1,117,146,31,25,1,-1,-1,-1,UAVSwarm-09

In [ ]:
# Drop rows with missing required fields
required_cols = ["frame", "x", "y", "width", "height", "confidence"]
df = df.dropna(subset=required_cols)

In [ ]:
df = df[
    (df["width"] > 0) &
    (df["height"] > 0)
]

In [ ]:
df = df[
    (df["confidence"] >= 0.0) &
    (df["confidence"] <= 1.0)
]

In [ ]:
df = df[df["frame"] >= 0]
df["frame"] = df["frame"].astype(int)

In [ ]:
df = df.drop(columns=["object_id", "ignore_1", "ignore_2", "ignore_3","Swarm"])

In [ ]:
print("Cleaned dataset shape:", df.shape)
df.describe()

Cleaned dataset shape: (49661, 6)

,frame,x,y,width,height,confidence
count,49661.000000,49661.000000,49661.000000,49661.000000,49661.000000,49661.0
mean,112.514488,486.237530,267.927609,29.037273,20.514468,1.0
std,96.879226,343.907457,186.502369,38.867826,15.002751,0.0
min,1.000000,-52.000000,-56.000000,10.000000,10.000000,1.0
25%,45.000000,236.000000,148.000000,17.000000,14.000000,1.0
50%,89.000000,403.000000,228.000000,21.000000,17.000000,1.0
75%,147.000000,635.000000,334.000000,28.000000,21.000000,1.0
max,653.000000,1908.000000,929.000000,780.000000,331.000000,1.0

In [ ]:
df.to_csv("detections_cleaned.csv", index=False)